apiVersion: apps/v1
kind: Deployment
metadata:
  name: drkiq  
  labels:
    app: drkiq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drkiq  
  template:
    metadata:      
      labels:
        app: drkiq
    spec:
      containers:
      - env:
        - name: CACHE_URL
          valueFrom:
            configMapKeyRef:
              key: CACHE_URL
              name: env
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              key: DATABASE_URL
              name: env
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              key: GROUP_ID
              name: env
        - name: JOB_WORKER_URL
          valueFrom:
            configMapKeyRef:
              key: JOB_WORKER_URL
              name: env
        - name: LISTEN_ON
          valueFrom:
            configMapKeyRef:
              key: LISTEN_ON
              name: env
        - name: SECRET_TOKEN
          valueFrom:
            configMapKeyRef:
              key: SECRET_TOKEN
              name: env
        - name: USER_ID
          valueFrom:
            configMapKeyRef:
              key: USER_ID
              name: env
        - name: WORKER_PROCESSES
          valueFrom:
            configMapKeyRef:
              key: WORKER_PROCESSES
              name: env
        image: drkiq
        imagePullPolicy: ""
        name: drkiq
        ports:
        - containerPort: 8010
        
---

apiVersion: v1
kind: Service
metadata:
  name: drkiq  
  labels:
    app: drkiq
spec:
  ports:
  - name: "8010"
    port: 8010
    targetPort: 8010
  selector:
    app: drkiq
