apiVersion: apps/v1
kind: Deployment
metadata:  
  name: postgres
  labels:
    app: postgres  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:      
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: test_db_password
        - name: POSTGRES_USER
          value: drkiq
        image: postgres:12.1
        imagePullPolicy: ""
        name: postgres
        ports:
        - containerPort: 5432
        resources:
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: drkiq-postgres
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: drkiq-postgres
        persistentVolumeClaim:
          claimName: drkiq-postgres

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres  
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres

