apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: drkiq-postgres 
  labels:
    app: drkiq-postgres  
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi